name: build

on: [push, pull_request]

# Workaround until https://github.com/DeLaGuardo/setup-clojure/issues/17 is fixed
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Java LTS
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install Clojure CLI
        uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: latest

      - name: Construct git info
        run: clojure -Srepro -M:git-info-edn
      - name: Check code
        run: clojure -Srepro -M:check
