name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Java LTS
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install Clojure CLI
        uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: latest

      - name: Construct git info
        run: clojure -Srepro -Agit-info-edn
      - name: Check code
        run: clojure -Srepro -Acheck
      - name: Check for outdated dependencies
        run: clojure -Srepro -Aoutdated
